---
title: "Homework 4 Problem 2"
output:
  html_document: 
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(janitor)
```

### Problem 2

The code below reads, cleans, and merges the `pols-month` and `GDP` data from the 538 datasets.

```{r tidy_data}
pols = read_csv("data/pols-month.csv") %>%
  clean_names() %>%
  mutate(month = lubridate::floor_date(mon, unit = "month")) %>%
  select(month, prez_dem)

gdp = read_csv("data/GDP.csv", na = ".") %>%
  clean_names() %>%
  mutate(month = lubridate::floor_date(date, unit = "month")) %>%
  select(month, gdp = value)

data_538 = right_join(pols, gdp, by = "month")
```

Given these data, we make a plot showing quarterly GDP since 1947; the party of the president is shown through color. 

```{r}
data_538 %>%
  mutate(prez_party = recode(prez_dem, `1` = "democrat", `0` = "republican")) %>% 
  ggplot(aes(x = month, y = gdp, color = prez_party)) + 
  geom_point()
```

Although quarterly GDP has varied substantially in the last 60 years, it is not immediately obvious that the president's party is a useful predictor of GDP. 